import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js';
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged, updateProfile } from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js';
import { getDatabase, ref, set, update, get, onValue, onChildAdded, onDisconnect, push, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-database.js';
import { firebaseConfig, FIREBASE_ENABLED } from './firebase-config.js';
import { TRUTHS, DARES } from './data/prompts.js';

const $=s=>document.querySelector(s); const screens=[...document.querySelectorAll('.screen')];
const state={mode:'local',players:[],current:0,turn:1,room:null,uid:null,isHost:false,me:null,roomData:null,type:null,challenge:'',timer:null,prepEnd:0,challengeEnd:0,stream:null,peers:new Map(),signalUnsubs:[],config:{truthPrep:30,darePrep:30,challenge:120,music:'',autoMedia:false}};
const ADMIN_UID='eSZBGSabJ5UMBcXhaGooD2sC8Rq2';
let app,auth,db;
const show=id=>{screens.forEach(x=>x.classList.remove('active')); $('#'+id)?.classList.add('active');};
const toast=t=>{const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2600)};
const beep=(f=520,d=.08)=>{try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;o.type='sine';g.gain.value=.035;o.connect(g);g.connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.stop(c.currentTime+d)}catch{}};
const vib=p=>navigator.vibrate?.(p);
const esc=v=>{const d=document.createElement('div');d.textContent=v;return d.innerHTML};
const uid=()=>auth?.currentUser?.uid;

for(let i=1;i<=50;i++){const o=document.createElement('option');o.value=i;o.textContent=`${i} ${i===1?'player':'players'}`;$('#playerCount').appendChild(o)} $('#playerCount').value=4; renderFields();
$('#playerCount').onchange=renderFields; function renderFields(){const n=+$('#playerCount').value,b=$('#playerFields');b.innerHTML='';for(let i=1;i<=n;i++){const x=document.createElement('input');x.id='p'+i;x.placeholder=`Player ${i} name`;b.appendChild(x)}}

function init(){if(!FIREBASE_ENABLED){show('auth');toast('Add Firebase configuration first.');return} app=initializeApp(firebaseConfig);auth=getAuth(app);db=getDatabase(app);onAuthStateChanged(auth,async user=>{if(!user){show('auth');return} state.uid=user.uid; const snap=await get(ref(db,'users/'+user.uid)); if(!snap.exists()) await set(ref(db,'users/'+user.uid),{displayName:user.displayName||user.email?.split('@')[0]||'Player'}); $('#home .lead').textContent=`Signed in as ${user.email}. Create a private room or play locally.`; $('#adminBtn').classList.toggle('hidden',user.uid!==ADMIN_UID); show('home'); loadConfig();});}
init();

let registerMode=false; $('#toggleAuth').onclick=()=>{registerMode=!registerMode;$('#authTitle').textContent=registerMode?'Create your account':'Sign in to play';$('#authButton').textContent=registerMode?'Create account':'Sign in';$('#authName').classList.toggle('hidden',!registerMode);$('#toggleAuth').textContent=registerMode?'Already have an account? Sign in':'Create an account'};
$('#authButton').onclick=async()=>{const email=$('#authEmail').value.trim(),pass=$('#authPassword').value,name=$('#authName').value.trim()||'Player';if(!email||pass.length<6){toast('Use a valid email and a password of at least 6 characters.');return}try{let cred;if(registerMode){cred=await createUserWithEmailAndPassword(auth,email,pass);await updateProfile(cred.user,{displayName:name});await set(ref(db,'users/'+cred.user.uid),{displayName:name});}else cred=await signInWithEmailAndPassword(auth,email,pass);toast('Signed in.')}catch(e){toast(e.message.replace('Firebase: ','').replace(/\s*\(auth\/[^)]+\)\.?/,'').trim())}};
$('#logoutBtn').onclick=()=>signOut(auth);
$('#adminClaim').classList.add('hidden');
$('#localBtn').onclick=()=>show('setup'); $('#setupBack').onclick=()=>show('home');
$('#startLocal').onclick=()=>{state.mode='local';state.players=[];for(let i=1;i<=+$('#playerCount').value;i++)state.players.push({id:'p'+i,name:$('#p'+i).value.trim()||`Player ${i}`,done:false});state.current=0;state.turn=1;startTurn()};
$('#createBtn').onclick=()=>openOnline('create'); $('#joinBtn').onclick=()=>openOnline('join'); $('#onlineBack').onclick=()=>show('home');

function startTurn(){show('game');$('#currentPlayer').textContent=state.players[state.current].name;$('#turnNumber').textContent=String(state.turn).padStart(2,'0');const active=state.mode==='local'||state.players[state.current].id===uid();$('#spinButton').disabled=!active;$('#turnHint').textContent=active?'You are up. Spin the bottle.':'Waiting for the current player to spin.';$('#spinStatus').textContent=active?'Ready.':'Waiting for player…';}
$('#spinButton').onclick=spin;
function chooseType(){return Math.random()<.5?'TRUTH':'DARE'}
async function spin(){if($('#spinButton').disabled)return;$('#spinButton').disabled=true;$('#spinStatus').textContent='Bottle spinning…';beep(700,.12);vib([30,40,30]);const type=chooseType(),deg=2160+Math.floor(Math.random()*2160);$('#bottle').style.transform=`rotate(${deg}deg)`;setTimeout(async()=>{state.type=type;beep(type==='TRUTH'?540:760,.16);if(state.mode==='online')await update(ref(db,'rooms/'+state.room),{status:'result',type,current:state.current,currentUid:state.players[state.current].id,challenge:'',updatedAt:serverTimestamp()});else openResult();},4200)}

function openResult(){show('result');$('#resultType').textContent=state.type;$('#resultSymbol').textContent=state.type==='TRUTH'?'T':'D';$('#resultPlayer').textContent=state.players[state.current].name;$('#challengeInput').value='';$('#challengeTextPreview').classList.add('hidden');$('#startChallenge').classList.add('hidden');const seconds=state.type==='TRUTH'?state.config.truthPrep:state.config.darePrep;state.prepEnd=Date.now()+seconds*1000;tickPrep();clearInterval(state.timer);state.timer=setInterval(tickPrep,250);$('#hostInputWrap').classList.remove('hidden')}
function tickPrep(){const left=Math.max(0,state.prepEnd-Date.now()),s=Math.ceil(left/1000),total=(state.type==='TRUTH'?state.config.truthPrep:state.config.darePrep);$('#prepTimer').textContent=`00:${String(s).padStart(2,'0')}`;$('#prepProgress').style.width=`${Math.min(100,left/(total*1000)*100)}%`;if(left===0){clearInterval(state.timer);if(!state.challenge)submitChallenge(true)}}
$('#submitChallenge').onclick=()=>submitChallenge(false);
async function submitChallenge(auto){const txt=$('#challengeInput').value.trim();if(!txt&&!auto){toast('Enter a challenge.');return}state.challenge=txt||randomPrompt(state.type);if(state.mode==='online')await update(ref(db,'rooms/'+state.room),{status:'result',challenge:state.challenge,updatedAt:serverTimestamp()});else openChallengeReady();}
function randomPrompt(t){const a=t==='TRUTH'?TRUTHS:DARES;return a[Math.floor(Math.random()*a.length)]}
function openChallengeReady(){clearInterval(state.timer);$('#hostInputWrap').classList.add('hidden');$('#challengeTextPreview').textContent=state.challenge;$('#challengeTextPreview').classList.remove('hidden');$('#startChallenge').classList.remove('hidden');}
$('#startChallenge').onclick=async()=>{if(state.mode==='online'){await update(ref(db,'rooms/'+state.room),{status:'challenge',challenge:state.challenge,challengeStartedAt:Date.now(),updatedAt:serverTimestamp()});}else startChallenge();};
function startChallenge(){show('challenge');$('#challengeType').textContent=state.type;$('#challengePlayer').textContent=state.players[state.current].name;$('#challengeText').textContent=state.challenge;$('#mediaConsent').classList.remove('hidden');clearMedia();state.challengeEnd=Date.now()+state.config.challenge*1000;tickChallenge();clearInterval(state.timer);state.timer=setInterval(tickChallenge,250);beep(820,.12);vib([50,60,50]);if(state.config.autoMedia&&state.mode==='local')enableMedia()}
function tickChallenge(){const left=Math.max(0,state.challengeEnd-Date.now()),sec=Math.ceil(left/1000),m=Math.floor(sec/60),s=sec%60;$('#challengeTimer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('#challengeProgress').style.width=`${Math.min(100,left/(state.config.challenge*1000)*100)}%`;if(left===0){clearInterval(state.timer);finishTurn(false)}}
$('#doneButton').onclick=()=>finishTurn(true);$('#failedButton').onclick=()=>finishTurn(false);
async function finishTurn(done){clearInterval(state.timer);clearMedia();if(state.mode==='online'){if(state.players[state.current]?.id!==uid()&&!state.isHost)return;const next=state.current+1;if(next>=state.players.length){await update(ref(db,'rooms/'+state.room),{status:'finished',updatedAt:serverTimestamp()});}else{const p=state.players[next];await update(ref(db,'rooms/'+state.room),{status:'playing',current:next,currentUid:p.id,turn:(state.turn||1)+1,updatedAt:serverTimestamp()})}return}state.players[state.current].done=done;state.current++;state.turn++;if(state.current>=state.players.length){finishLocal();return}setTimeout(startTurn,450)}
function finishLocal(){show('finish');$('#scoreboard').innerHTML=state.players.map((p,i)=>`<div class="score-row"><span>${i+1}. ${esc(p.name)}</span><b>${p.done?'COMPLETED':'FAILED'}</b></div>`).join('')}

function openOnline(kind){show('online');$('#onlineEyebrow').textContent=kind==='create'?'CREATE ROOM':'JOIN ROOM';$('#onlineTitle').textContent=kind==='create'?'Create a private room':'Join a private room';$('#onlineContent').innerHTML=kind==='create'?`<input id="onlineName" maxlength="32" placeholder="Your display name"><button class="btn primary full" id="createRoom">Create private room</button>`:`<input id="onlineName" maxlength="32" placeholder="Your display name"><input id="joinCode" maxlength="6" placeholder="6-character room code" style="text-transform:uppercase"><button class="btn primary full" id="joinRoom">Join private room</button>`}
document.addEventListener('click',e=>{if(e.target.id==='createRoom')createRoom();if(e.target.id==='joinRoom')joinRoom();if(e.target.id==='beginOnline')beginOnline();if(e.target.id==='leaveRoom')leaveRoom();if(e.target.id==='newGame')show('home');if(e.target.id==='enableMedia')enableMedia();if(e.target.id==='adminBtn')openAdmin();if(e.target.id==='adminHome')show('home');if(e.target.id==='saveConfig')saveConfig();if(e.target.id==='savePrompts')savePrompts()});
const roomCode=()=>Math.random().toString(36).slice(2,8).toUpperCase();
async function createRoom(){const name=$('#onlineName').value.trim()||auth.currentUser.displayName||'Host';state.room=roomCode();state.mode='online';state.isHost=true;state.me={id:uid(),name,host:true,online:true};await set(ref(db,'rooms/'+state.room),{status:'lobby',hostUid:uid(),createdAt:serverTimestamp(),updatedAt:serverTimestamp(),players:{[uid()]:state.me}});await set(ref(db,'users/'+uid()+'/displayName'),name);await onDisconnect(ref(db,'rooms/'+state.room+'/players/'+uid()+'/online')).set(false);listenRoom();show('lobby')}
async function joinRoom(){const code=$('#joinCode').value.trim().toUpperCase();if(!/^[A-Z0-9]{6}$/.test(code)){toast('Enter a valid 6-character code.');return}const snap=await get(ref(db,'rooms/'+code));if(!snap.exists()){toast('Room not found.');return}const d=snap.val();if(d.status!=='lobby'){toast('This room has already started.');return}const name=$('#onlineName').value.trim()||auth.currentUser.displayName||'Player';state.room=code;state.mode='online';state.isHost=false;state.me={id:uid(),name,host:false,online:true};await set(ref(db,'rooms/'+code+'/players/'+uid()),state.me);await onDisconnect(ref(db,'rooms/'+code+'/players/'+uid()+'/online')).set(false);listenRoom();show('lobby')}
function listenRoom(){onValue(ref(db,'rooms/'+state.room),snap=>{const d=snap.val();if(!d){show('home');toast('Room closed.');return}state.roomData=d;state.players=Object.values(d.players||{}).filter(p=>p.online!==false);state.isHost=d.hostUid===uid();$('#roomCodeBig').textContent=state.room;$('#lobbyPlayers').innerHTML=state.players.map((p,i)=>`<div class="lobby-player join-anim"><span>${i+1}. ${esc(p.name)}</span><small>${p.host?'HOST':'ONLINE'}</small></div>`).join('');$('#beginOnline').classList.toggle('hidden',!(state.isHost&&d.status==='lobby'&&state.players.length>0));if(d.status==='playing'){state.current=d.current;state.turn=d.turn;startTurnOnline(d)}if(d.status==='result'){state.current=d.current;state.turn=d.turn;state.type=d.type;state.challenge=d.challenge||'';openResultOnline(d)}if(d.status==='challenge'){state.current=d.current;state.turn=d.turn;state.type=d.type;state.challenge=d.challenge;startChallengeOnline(d)}if(d.status==='finished'){clearMedia();finishOnline(d)}})}
async function beginOnline(){if(!state.isHost)return;const first=state.players[0];await update(ref(db,'rooms/'+state.room),{status:'playing',current:0,currentUid:first.id,turn:1,updatedAt:serverTimestamp()})}
function startTurnOnline(d){show('game');const p=state.players[d.current];$('#currentPlayer').textContent=p?.name||'Player';$('#turnNumber').textContent=String(d.turn||1).padStart(2,'0');const active=p?.id===uid();$('#spinButton').disabled=!active;$('#turnHint').textContent=active?'Your turn — spin the bottle.':'Waiting for '+(p?.name||'player')+' to spin.';$('#spinStatus').textContent=active?'Ready.':'Waiting for current player…'}
function openResultOnline(d){show('result');$('#resultType').textContent=d.type;$('#resultSymbol').textContent=d.type==='TRUTH'?'T':'D';$('#resultPlayer').textContent=state.players[d.current]?.name||'Player';$('#hostInputWrap').classList.toggle('hidden',state.players[d.current]?.id===uid());$('#challengeTextPreview').textContent=d.challenge||'';$('#challengeTextPreview').classList.toggle('hidden',!d.challenge);$('#startChallenge').classList.toggle('hidden',!d.challenge);const total=d.type==='TRUTH'?state.config.truthPrep:state.config.darePrep;state.prepEnd=Date.now()+total*1000;tickPrep();clearInterval(state.timer);state.timer=setInterval(tickPrep,250)}
function startChallengeOnline(d){show('challenge');$('#challengeType').textContent=d.type;$('#challengePlayer').textContent=state.players[d.current]?.name||'Player';$('#challengeText').textContent=d.challenge;$('#mediaConsent').classList.toggle('hidden',state.players[d.current]?.id!==uid());clearMedia();state.challengeEnd=(d.challengeStartedAt||Date.now())+state.config.challenge*1000;tickChallenge();clearInterval(state.timer);state.timer=setInterval(tickChallenge,250);setupRtcForRoom(d);if(state.players[d.current]?.id===uid()&&state.config.autoMedia)enableMedia()}
function finishOnline(d){show('finish');$('#scoreboard').innerHTML=state.players.map((p,i)=>`<div class="score-row"><span>${i+1}. ${esc(p.name)}</span><b>PLAYER ${i+1}</b></div>`).join('')}
async function leaveRoom(){try{await set(ref(db,'rooms/'+state.room+'/players/'+uid()),null)}catch{}clearMedia();show('home')}

async function enableMedia(){if(state.mode==='online'&&state.players[state.current]?.id!==uid()){toast('Only the active player can enable camera/microphone.');return}try{state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:720},height:{ideal:720}},audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});$('#mediaConsent').classList.add('hidden');renderLocalVideo();if(state.mode==='online')await publishOfferToRoom();}catch(e){toast('Camera/microphone permission was not granted.')}}
function renderLocalVideo(){const grid=$('#mediaGrid');grid.innerHTML='';const wrap=document.createElement('div');wrap.className='video-tile active-video';wrap.innerHTML='<span>YOU • LIVE</span><video autoplay playsinline muted></video>';wrap.querySelector('video').srcObject=state.stream;grid.appendChild(wrap)}
function clearMedia(){if(state.stream){state.stream.getTracks().forEach(t=>t.stop());state.stream=null}state.peers.forEach(pc=>pc.close());state.peers.clear();$('#mediaGrid').innerHTML='';state.signalUnsubs.forEach(u=>u&&u());state.signalUnsubs=[]}
function peer(id){if(state.peers.has(id))return state.peers.get(id);const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});state.peers.set(id,pc);pc.onicecandidate=e=>{if(e.candidate)sendSignal(id,{kind:'candidate',payload:JSON.stringify(e.candidate)})};pc.ontrack=e=>renderRemoteVideo(id,e.streams[0]);if(state.stream)state.stream.getTracks().forEach(t=>pc.addTrack(t,state.stream));return pc}
async function sendSignal(to,msg){await set(push(ref(db,`rooms/${state.room}/rtc/${uid()}/${to}`)),msg)}
async function publishOfferToRoom(){for(const p of state.players){if(p.id===uid())continue;const pc=peer(p.id);const offer=await pc.createOffer();await pc.setLocalDescription(offer);await sendSignal(p.id,{kind:'offer',payload:JSON.stringify(offer)})}}
function setupRtcForRoom(d){state.signalUnsubs.forEach(u=>u&&u());state.signalUnsubs=[];for(const p of state.players){if(p.id===uid())continue;const r=ref(db,`rooms/${state.room}/rtc/${p.id}/${uid()}`);const unsub=onChildAdded(r,async snap=>{const msg=snap.val();const pc=peer(p.id);if(msg.kind==='offer'){await pc.setRemoteDescription(JSON.parse(msg.payload));const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await sendSignal(p.id,{kind:'answer',payload:JSON.stringify(answer)})}else if(msg.kind==='answer'){await pc.setRemoteDescription(JSON.parse(msg.payload))}else if(msg.kind==='candidate'){try{await pc.addIceCandidate(JSON.parse(msg.payload))}catch{}}});state.signalUnsubs.push(unsub)}}
function renderRemoteVideo(id,stream){let wrap=document.querySelector(`[data-peer="${id}"]`);if(!wrap){wrap=document.createElement('div');wrap.className='video-tile';wrap.dataset.peer=id;wrap.innerHTML='<span>LIVE</span><video autoplay playsinline></video>';$('#mediaGrid').appendChild(wrap)}wrap.querySelector('video').srcObject=stream}

async function loadConfig(){try{const s=await get(ref(db,'config'));if(s.exists())state.config={...state.config,...s.val()};applyConfig()}catch{}}
function applyConfig(){const c=state.config;$('#cfgTruthPrep').value=c.truthPrep;$('#cfgDarePrep').value=c.darePrep;$('#cfgChallenge').value=c.challenge;$('#cfgMusic').value=c.music||'';$('#cfgAutoMedia').checked=!!c.autoMedia;const a=$('#bgMusic');if(c.music){a.src=c.music;a.volume=.22;document.addEventListener('click',()=>a.play().catch(()=>{}),{once:true})}}
function openAdmin(){show('admin');loadConfig();get(ref(db,'config/prompts')).then(s=>{$('#cfgPrompts').value=Array.isArray(s.val())?s.val().join('\n'):''})}
async function saveConfig(){try{const token=await auth.currentUser.getIdTokenResult(true);if(auth.currentUser?.uid!==ADMIN_UID){toast('Admin only.');return}await update(ref(db,'config'),{truthPrep:Math.max(5,Math.min(120,+$('#cfgTruthPrep').value||30)),darePrep:Math.max(5,Math.min(120,+$('#cfgDarePrep').value||30)),challenge:Math.max(30,Math.min(600,+$('#cfgChallenge').value||120)),music:$('#cfgMusic').value.trim(),autoMedia:$('#cfgAutoMedia').checked});await loadConfig();toast('Configuration saved.')}catch(e){toast('Could not save configuration.')}}
async function savePrompts(){try{const token=await auth.currentUser.getIdTokenResult(true);if(auth.currentUser?.uid!==ADMIN_UID){toast('Admin only.');return}const arr=$('#cfgPrompts').value.split('\n').map(x=>x.trim()).filter(Boolean).slice(0,500);await set(ref(db,'config/prompts'),arr);toast('Custom prompts saved.')}catch{toast('Could not save prompts.')}}
$('#adminBtn').onclick=openAdmin;
